# Definición del lenguaje que se usará
language: python
# Definición de la versión del lenguaje que se usará
python:
  - "3.3"
  - "3.5"
  - "3.6"
# Instalación de requerimientos
install:
  - pip install -r requeriments.txt
# Comando para ejecutar el test
script:
  - pytest
